version: '3'
services:
  webapp:
    build: .
    container_name: webapp
    volumes:
      - .:/var/www
      - /root/.ssh:/root/.ssh
    working_dir: /var/www/
    links:
      - nginx
      - mysql
    tty: true

  mysql:
    image: mysql:5.7
    container_name: zstack-mysql
    ports:
      - 3307:3306
    command: mysqld --sql_mode="ERROR_FOR_DIVISION_BY_ZERO"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: my_secret
       MYSQL_DATABASE: santa
       MYSQL_USER: santa_user
       MYSQL_PASSWORD: santa_password

  phpfpm:
    build: docker/phpfpm
    container_name: zstack-phpfpm
    ports:
      - 9001:9000
    volumes:
      - .:/var/www
    environment:
      - XDEBUG_CONFIG=remote_host=172.17.0.1
      - PHP_IDE_CONFIG=serverName=localhost
      - ./docker/phpfpm/log/error.log:/var/log/error.log
    env_file: vars.env

  nginx:
    build: docker/nginx
    container_name: zstack-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/log:/var/log/nginx
    links:
      - phpfpm
