# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/ind*ex.html
fos_rest:
    param_fetcher_listener: true
    body_converter:
        enabled: true
    view:
        view_response_listener: force
        formats:
            json: true
    service:
        serializer: fos_rest.serializer.jms
    serializer:
        serialize_null: true
    exception:
        exception_controller: 'App\Controller\CustomExceptionController::showAction'
        enabled: true
    format_listener:
        rules:
            - { path : ^/api/doc ,priorities: json, fallback_format: false, prefer_extension: false }
            - { path : ^/ ,priorities: [json], fallback_format: json, prefer_extension: false }
